export interface Resource {
  slug: string;
  title: string;
  author?: string;
  traditionSlug: string;
  traditionSlugs?: string[];
  perspectiveType: "devotional" | "questioning" | "academic" | "personal";
  type: string;
  summary: string;
  editorialSummary?: string;
  sourceUrl?: string;
  hostedLocally?: boolean;
  license?: string;
  priority?: number;
  difficulty?: "beginner" | "intermediate" | "advanced";
  format?: string;
  affiliateEligible?: boolean;
  datePublished?: string;
  tags: string[];
  pairedWith?: string;
}

const resources: Resource[] = [
  {
    slug: "an-olive-branch",
    title: "An Olive Branch",
    author: "Independent Organization",
    traditionSlug: "buddhism",
    perspectiveType: "academic",
    type: "document/reports",
    summary: "Independent organization that conducted third-party investigations into abuse at Buddhist organizations including Shambhala and Against the Stream. Reports are publicly released.",
    sourceUrl: "an-olive-branch.org",
    hostedLocally: true,
    license: "standard-copyright",
    priority: 5,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "2021-2023",
    tags: ["investigation","abuse","institutional","reports"],
  },
  {
    slug: "behind-bastards-buddhism",
    title: "Behind the Bastards (Buddhist Episodes)",
    author: "Robert Evans (Host)",
    traditionSlug: "buddhism",
    perspectiveType: "academic",
    type: "podcast",
    summary: "Episodes of the popular podcast covering abusive Buddhist leaders and organizations.",
    sourceUrl: "iheartmedia.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "podcast-app",
    datePublished: "2016-ongoing",
    tags: ["podcast","history","abuse","popular"],
  },
  {
    slug: "guru-papers",
    title: "The Guru Papers",
    author: "Joel Kramer & Diana Alstad",
    traditionSlug: "buddhism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Essential analysis of guru-disciple dynamics and authoritarian control in spiritual movements. Examines how spiritual authority is constructed and exploited across traditions.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 5,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1993",
    tags: ["guru","authority","psychology","analysis"],
  },
  {
    slug: "holy-hell",
    title: "Holy Hell",
    author: "Will Allen (Director)",
    traditionSlug: "buddhism/yoga",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Documentary about the Buddhafield cult and its leader Michel. Filmed over 22 years by a former member.",
    sourceUrl: "streaming",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2016",
    tags: ["documentary","buddhafield","cult","yoga"],
  },
  {
    slug: "sex-violence-tibetan-buddhism",
    title: "Sex and Violence in Tibetan Buddhism",
    author: "Ian Finnigan",
    traditionSlug: "buddhism (tibetan)",
    perspectiveType: "questioning",
    type: "book",
    summary: "Academic examination of sexual abuse and violence within Tibetan Buddhist institutions.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2016",
    tags: ["tibetan","abuse","scholarship","criticism"],
  },
  {
    slug: "shambhala-reports",
    title: "Shambhala Abuse Reports",
    author: "Shambhala International Board",
    traditionSlug: "buddhism",
    perspectiveType: "academic",
    type: "document",
    summary: "Collection of reports documenting sexual abuse within the Shambhala Buddhist organization, particularly by its leader Sakyong Mipham Rinpoche.",
    sourceUrl: "shambhala.report",
    hostedLocally: true,
    license: "standard-copyright",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "2019-2020",
    tags: ["abuse","shambhala","investigation","institutional"],
  },
  {
    slug: "shambhala-subreddit",
    title: "r/ShambhalaBuddhism",
    author: "Reddit Community",
    traditionSlug: "buddhism",
    perspectiveType: "questioning",
    type: "subreddit",
    summary: "Subreddit discussing Shambhala Buddhism, including abuse allegations and community responses.",
    sourceUrl: "reddit.com/r/ShambhalaBuddhism",
    license: "reddit-tos",
    priority: 3,
    difficulty: "intermediate",
    format: "reddit",
    datePublished: "2010-ongoing",
    tags: ["community","shambhala","discussion"],
  },
  {
    slug: "bart-ehrman-blog",
    title: "Bart Ehrman Blog",
    author: "Bart D. Ehrman",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "website",
    summary: "Blog by New Testament scholar Bart Ehrman covering biblical criticism and early Christianity.",
    sourceUrl: "https://ehrmanblog.org",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "free-online",
    tags: ["biblical-criticism","scholarship","blog","subscription"],
  },
  {
    slug: "born-again-again",
    title: "Born Again Again Podcast",
    author: "Born Again Again Podcast",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Podcast sharing stories of faith deconstruction and reconstruction from various perspectives.",
    sourceUrl: "https://www.bornagainagainpodcast.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "podcast-app",
    tags: ["podcast","deconstruction","personal-stories","community"],
  },
  {
    slug: "clergy-project",
    title: "The Clergy Project",
    author: "The Clergy Project",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "organization",
    summary: "Confidential online community for current and former religious leaders who no longer hold supernatural beliefs.",
    sourceUrl: "https://www.clergyproject.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "free-online",
    tags: ["clergy","support","career-transition","confidential"],
  },
  {
    slug: "dare-to-doubt",
    title: "Dare to Doubt",
    author: "Dare to Doubt",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "website",
    summary: "Website providing resources and community for people questioning or leaving Christian faith.",
    sourceUrl: "https://www.daretodoubt.org",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "free-online",
    tags: ["support","resources","deconstruction","community"],
  },
  {
    slug: "exchristian-subreddit",
    title: "r/exchristian",
    author: "Reddit user community",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "community",
    summary: "Major online community for ex-Christians with 100,000+ members.",
    sourceUrl: "https://www.reddit.com/r/exchristian",
    license: "reddit-tos",
    priority: 5,
    difficulty: "beginner",
    format: "reddit",
    tags: ["community","support","stories"],
  },
  {
    slug: "exvangelical",
    title: "Exvangelical Podcast",
    author: "Blake Chastain",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Podcast examining the exvangelical movement and experience of leaving evangelical Christianity.",
    sourceUrl: "https://www.exvangelicalpodcast.com",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "podcast-app",
    tags: ["podcast","evangelical","deconstruction","culture"],
  },
  {
    slug: "genetically-modified-skeptic",
    title: "Genetically Modified Skeptic",
    author: "Drew (Genetically Modified Skeptic)",
    traditionSlug: "christianity",
    perspectiveType: "devotional",
    type: "youtube",
    summary: "YouTube channel by a former fundamentalist Christian examining religious claims and apologetics.",
    sourceUrl: "https://www.youtube.com/@GeneticallyModifiedSkeptic",
    license: "youtube-standard",
    priority: 4,
    difficulty: "beginner",
    format: "youtube",
    tags: ["youtube","deconstruction","personal-story","apologetics"],
  },
  {
    slug: "godless-dan-barker",
    title: "Godless",
    author: "Dan Barker",
    traditionSlug: "christianity",
    perspectiveType: "personal",
    type: "book",
    summary: "Memoir by Dan Barker documenting his 19 years as an evangelical minister and deconversion.",
    sourceUrl: "https://www.amazon.com/Godless-Former-Minister-Examines-Christianity/dp/1569756775",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2008",
    tags: ["memoir","clergy","deconversion","atheism"],
  },
  {
    slug: "holy-koolaid",
    title: "Holy Koolaid",
    author: "Holy Koolaid",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "YouTube channel examining religious claims through a scientific lens.",
    sourceUrl: "https://www.youtube.com/@HolyKoolaid",
    license: "youtube-standard",
    priority: 3,
    difficulty: "intermediate",
    format: "youtube",
    tags: ["youtube","science","skepticism","debunking"],
  },
  {
    slug: "jesus-camp",
    title: "Jesus Camp",
    author: "Heidi Ewing & Rachel Grady",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Oscar-nominated documentary following children at evangelical summer camp.",
    sourceUrl: "https://www.documentaryheaven.com/jesus-camp/",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2006",
    tags: ["documentary","evangelical","children","indoctrination"],
  },
  {
    slug: "jesus-interrupted",
    title: "Jesus, Interrupted",
    author: "Bart D. Ehrman",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "book",
    summary: "Ehrman's examination of contradictions within the New Testament and Gospel assemblies.",
    sourceUrl: "https://www.amazon.com/Jesus-Interrupted-Revealing-Contradictions-Bible/dp/0061778184",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2009",
    tags: ["biblical-criticism","contradictions","scholarship","new-testament"],
  },
  {
    slug: "josh-harris",
    title: "Josh Harris Public Deconstruction",
    author: "Josh Harris",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "Content by Josh Harris, author of 'I Kissed Dating Goodbye,' publicly deconstructing his faith.",
    sourceUrl: "https://www.youtube.com/@joshharris3962",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "youtube",
    tags: ["purity-culture","i-kissed-dating-goodbye","public-deconstruction"],
  },
  {
    slug: "journey-free",
    title: "Journey Free",
    author: "Dr. Marlene Winell",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "organization",
    summary: "Organization founded by Dr. Marlene Winell, who coined the term 'Religious Trauma Syndrome.",
    sourceUrl: "https://www.journeyfree.org",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "free-online",
    tags: ["religious-trauma","therapy","RTS","psychology"],
  },
  {
    slug: "leaving-the-fold",
    title: "Leaving the Fold",
    author: "Dr. Marlene Winell",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "book",
    summary: "The foundational book on recovering from religious indoctrination.",
    sourceUrl: "https://www.amazon.com/Leaving-Fold-Guide-Religious-Indoctrination/dp/0929355205",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1993",
    tags: ["religious-trauma","recovery","psychology","self-help"],
  },
  {
    slug: "misquoting-jesus",
    title: "Misquoting Jesus",
    author: "Bart D. Ehrman",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "book",
    summary: "Bestselling examination of how the Bible was changed by scribes over centuries.",
    sourceUrl: "https://www.amazon.com/Misquoting-Jesus-Story-Behind-Changed/dp/0060859512",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2005",
    tags: ["biblical-criticism","textual-analysis","scholarship","new-testament"],
  },
  {
    slug: "pure-linda-kay-klein",
    title: "Pure",
    author: "Linda Kay Klein",
    traditionSlug: "christianity",
    perspectiveType: "personal",
    type: "book",
    summary: "Investigation of evangelical purity culture and its lasting psychological damage.",
    sourceUrl: "https://www.amazon.com/Pure-Inside-Movement-Affects-Girls/dp/1492273783",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2018",
    tags: ["purity-culture","sexuality","women","memoir"],
  },
  {
    slug: "recovering-from-religion",
    title: "Recovering from Religion",
    author: "Recovering from Religion (nonprofit)",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "organization",
    summary: "National nonprofit providing support for people leaving religion. Operates the 1-84-I-DOUBT-IT helpline.",
    sourceUrl: "https://www.recoveringfromreligion.org",
    license: "standard-copyright",
    priority: 5,
    difficulty: "beginner",
    format: "free-online",
    tags: ["support","hotline","cross-religion","nonprofit"],
  },
  {
    slug: "religious-trauma-institute",
    title: "Religious Trauma Institute",
    author: "Religious Trauma Institute",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "organization",
    summary: "Organization providing training for therapists on religious trauma and resources for survivors.",
    sourceUrl: "https://www.religioustraumainstitute.com",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "free-online",
    tags: ["religious-trauma","training","therapists","education"],
  },
  {
    slug: "secular-therapy-project",
    title: "Secular Therapy Project",
    author: "Recovering from Religion",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "directory",
    summary: "Directory of vetted secular therapists who won't push religious frameworks in treatment.",
    sourceUrl: "https://www.seculartherapy.org",
    license: "standard-copyright",
    priority: 5,
    difficulty: "beginner",
    format: "free-online",
    tags: ["therapy","directory","mental-health","practical"],
  },
  {
    slug: "shameless",
    title: "Shameless",
    author: "Nadia Bolz-Weber",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "book",
    summary: "Lutheran pastor Nadia Bolz-Weber challenging Christian sexual ethics and the shame they produce.",
    sourceUrl: "https://www.amazon.com/Shameless-A-Sexual-Reformation-Nadia/dp/0385542488",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2017",
    tags: ["sexuality","shame","progressive-Christianity","purity-culture"],
  },
  {
    slug: "shiny-happy-people",
    title: "Shiny Happy People",
    author: "Amazon Prime Video",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "2023 documentary exposing the Institute in Basic Life Principles and the Duggar family.",
    sourceUrl: "https://www.amazon.com/Shiny-Happy-People-Duggar-Family/dp/B0BQ7SY41Q",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2023",
    tags: ["documentary","duggar","IBLP","fundamentalism","abuse"],
  },
  {
    slug: "straight-white-american-jesus",
    title: "Straight White American Jesus Podcast",
    author: "Religion scholars (Du Mez, others)",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Academic podcast examining Christian nationalism and white evangelicalism in American politics.",
    sourceUrl: "https://www.podcastone.com/straight-white-american-jesus",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "podcast-app",
    tags: ["podcast","politics","christian-nationalism","culture"],
  },
  {
    slug: "the-god-delusion",
    title: "The God Delusion",
    author: "Richard Dawkins",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "book",
    summary: "Bestseller arguing against the existence of God from scientific and philosophical perspectives.",
    sourceUrl: "https://www.amazon.com/God-Delusion-Richard-Dawkins/dp/0618918248",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2006",
    tags: ["atheism","philosophy","science","arguments"],
  },
  {
    slug: "the-keepers",
    title: "The Keepers",
    author: "Netflix",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Netflix documentary about unsolved murder of nun and Catholic clergy sexual abuse cover-up.",
    sourceUrl: "https://www.netflix.com/search?q=the%20keepers",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "streaming",
    datePublished: "2017",
    tags: ["documentary","catholic","abuse","cover-up","true-crime"],
  },
  {
    slug: "the-liturgists",
    title: "The Liturgists Podcast",
    author: "Michael Gungor & Science Mike",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Podcast exploring faith, science, and the human experience for those questioning faith.",
    sourceUrl: "https://www.liturgists.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "podcast-app",
    tags: ["podcast","progressive","science","faith-transition"],
  },
  {
    slug: "theramintrees",
    title: "TheraminTrees",
    author: "TheraminTrees",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "Animated YouTube channel examining psychological manipulation in religion, relationships, and ideologies.",
    sourceUrl: "https://www.youtube.com/@TheraminTrees",
    license: "youtube-standard",
    priority: 4,
    difficulty: "advanced",
    format: "youtube",
    tags: ["youtube","psychology","manipulation","abuse","animation"],
  },
  {
    slug: "why-i-am-not-a-christian",
    title: "Why I Am Not a Christian",
    author: "Bertrand Russell",
    traditionSlug: "christianity",
    perspectiveType: "questioning",
    type: "essay",
    summary: "Classic 1927 lecture examining and rejecting arguments for Christianity.",
    sourceUrl: "https://www.archive.org/details/whyiamnotachrist_0",
    hostedLocally: true,
    license: "public-domain",
    priority: 3,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "1927",
    tags: ["philosophy","classic","arguments","atheism"],
  },
  {
    slug: "why-i-believed",
    title: "Why I Believed",
    author: "Kenneth W. Daniels",
    traditionSlug: "christianity",
    perspectiveType: "personal",
    type: "book",
    summary: "Former missionary's detailed account of losing faith and examining arguments that once convinced him.",
    sourceUrl: "https://www.amazon.com/Why-I-Believed-Kenneth-Daniels/dp/0985690143",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2012",
    tags: ["memoir","missionary","deconversion","evangelical"],
  },
  {
    slug: "bite-model-pdf",
    title: "BITE Model PDF",
    author: "Steven Hassan",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "document",
    summary: "The BITE Model (Behavior, Information, Thought, Emotional control) checklist for evaluating high-control groups. Free PDF download. BITE Model is trademarked by Steven Hassan.",
    sourceUrl: "freedomofmind.com",
    hostedLocally: true,
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "1988-ongoing",
    tags: ["framework","assessment","tool","psychology"],
  },
  {
    slug: "combating-cult-mind-control-general",
    title: "Combating Cult Mind Control",
    author: "Steven Hassan",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "book",
    summary: "Hassan's foundational work on understanding and recovering from cult mind control. Introduces the BITE Model framework.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1988",
    tags: ["psychology","mind-control","recovery","BITE-model"],
  },
  {
    slug: "cult-education-institute",
    title: "Cult Education Institute",
    author: "Rick Ross",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "website",
    summary: "Massive free library of thousands of articles about cults and high-control groups. Founded by cult intervention specialist Rick Ross.",
    sourceUrl: "culteducation.com",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "1996-ongoing",
    tags: ["archive","encyclopedia","articles","news"],
  },
  {
    slug: "cults-inside-out",
    title: "Cults Inside Out",
    author: "Rick Ross",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "book",
    summary: "Rick Ross's guide to understanding cults and the intervention process. Case studies from decades of cult intervention work.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2014",
    tags: ["intervention","psychology","case-studies"],
  },
  {
    slug: "cults-subreddit",
    title: "r/cults",
    author: "Reddit Community",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "subreddit",
    summary: "Active subreddit for discussing cults, identifying cult-like behavior, and supporting former members.",
    sourceUrl: "reddit.com/r/cults",
    license: "reddit-tos",
    priority: 4,
    difficulty: "beginner",
    format: "reddit",
    datePublished: "2010-ongoing",
    tags: ["community","discussion","identification","support"],
  },
  {
    slug: "escaping-twin-flames",
    title: "Escaping Twin Flames",
    author: "Amazon",
    traditionSlug: "new age/spiritual",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Amazon documentary exposing the Twin Flames Universe organization and its manipulative practices.",
    sourceUrl: "Amazon",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2022",
    tags: ["documentary","twin-flames","new-age","manipulation"],
  },
  {
    slug: "fbi-jonestown",
    title: "FBI Vault - Jonestown",
    author: "FBI",
    traditionSlug: "christianity",
    perspectiveType: "academic",
    type: "gov-document",
    summary: "FBI's declassified investigation files on Jonestown. US government works are public domain. Thousands of pages of primary source documents.",
    sourceUrl: "vault.fbi.gov/jonestown",
    hostedLocally: true,
    license: "public-domain",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "1978-ongoing",
    tags: ["FBI","primary-source","government","investigation"],
  },
  {
    slug: "heavens-gate",
    title: "Heaven's Gate Website",
    author: "TELAH Foundation",
    traditionSlug: "new age/christian syncretic",
    perspectiveType: "questioning",
    type: "website",
    summary: "The original Heaven's Gate cult website, maintained by surviving members of the TELAH Foundation. A unique primary source that remains online exactly as the cult left it.",
    sourceUrl: "heavensgate.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "1996-ongoing",
    tags: ["heavens-gate","website","primary-source","historical"],
  },
  {
    slug: "icsa",
    title: "ICSA (International Cultic Studies Association)",
    author: "ICSA",
    traditionSlug: "cross-tradition",
    perspectiveType: "academic",
    type: "organization",
    summary: "Academic organization studying cultic dynamics. Publishes the ICSA journal. Hosts conferences for researchers and former members.",
    sourceUrl: "internationalculticstudies.org",
    license: "standard-copyright",
    priority: 5,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "1979-ongoing",
    tags: ["academic","organization","research","journal"],
  },
  {
    slug: "jonestown-institute",
    title: "Jonestown Institute",
    author: "San Diego State University",
    traditionSlug: "christianity (christian apocalyptic)",
    perspectiveType: "academic",
    type: "academic/archive",
    summary: "San Diego State University's comprehensive archive on Peoples Temple and Jonestown. Includes FBI documents (public domain), survivor accounts, and academic analysis.",
    sourceUrl: "jonestown.sdsu.edu",
    hostedLocally: true,
    license: "mixed",
    priority: 5,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "1982-ongoing",
    tags: ["jonestown","archive","academic","primary-sources"],
  },
  {
    slug: "keep-sweet-netflix",
    title: "Keep Sweet: Pray and Obey",
    author: "Netflix",
    traditionSlug: "christianity (flds)",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Netflix documentary about Warren Jeffs and the FLDS community. Covers the history, practices, and eventual prosecution.",
    sourceUrl: "Netflix",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2022",
    tags: ["documentary","FLDS","warren-jeffs","polygamy"],
  },
  {
    slug: "not-without-my-sister",
    title: "Not Without My Sister",
    author: "Kristina Jones, Celeste Jones, Juliana Boerio-Goates",
    traditionSlug: "christianity (children of god/the family international)",
    perspectiveType: "personal",
    type: "book",
    summary: "Memoir by three sisters raised in the Children of God cult, documenting abuse and their escape.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2007",
    tags: ["memoir","children-of-god","family-international","child-abuse"],
  },
  {
    slug: "nxivm-court-docs",
    title: "NXIVM Court Documents",
    author: "US Federal Court",
    traditionSlug: "secular high-control group",
    perspectiveType: "questioning",
    type: "court-document",
    summary: "Federal court documents from the prosecution of Keith Raniere and other NXIVM leaders. Includes evidence of sex trafficking, forced labor, and branding.",
    sourceUrl: "PACER",
    hostedLocally: true,
    license: "public-domain",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "2017-2020",
    tags: ["NXIVM","court-documents","trial","trafficking"],
  },
  {
    slug: "seduced-nxivm",
    title: "Seduced",
    author: "Starz",
    traditionSlug: "secular high-control group",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Documentary series told from the perspective of India Oxenberg, who was recruited into NXIVM's inner circle.",
    sourceUrl: "Starz",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2020",
    tags: ["documentary","NXIVM","personal-story"],
  },
  {
    slug: "the-vow-hbo",
    title: "The Vow",
    author: "HBO",
    traditionSlug: "secular high-control group",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Multi-season HBO documentary following former NXIVM members and the effort to expose the organization.",
    sourceUrl: "HBO/Max",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2020-2021",
    tags: ["documentary","NXIVM","personal-stories","HBO"],
  },
  {
    slug: "warren-jeffs-records",
    title: "Warren Jeffs FLDS Court Records",
    author: "State Courts",
    traditionSlug: "christianity (flds)",
    perspectiveType: "questioning",
    type: "court-document",
    summary: "Court records from the prosecution of FLDS leader Warren Jeffs for sexual assault of minors. Documents systematic child marriage within the FLDS community.",
    sourceUrl: "state court records",
    hostedLocally: true,
    license: "public-domain",
    priority: 3,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "2006-2011",
    tags: ["FLDS","child-abuse","polygamy","court-documents"],
  },
  {
    slug: "conspiracy-psychology-subreddit",
    title: "r/conspiracy_psychology: Understanding Conspiracy Belief Formation",
    author: "Reddit Community",
    traditionSlug: "general",
    perspectiveType: "questioning",
    type: "website",
    summary: "Academic and lay psychology-focused discussion community examining the cognitive and psychological mechanisms underlying conspiracy theory belief and radicalization",
    sourceUrl: "https://www.reddit.com/r/conspiracy_psychology/",
    license: "Creative Commons - CC BY-NC-SA 4.0",
    priority: 3,
    difficulty: "intermediate",
    format: "website",
    datePublished: "2020-03-01",
    tags: [],
  },
  {
    slug: "conspirituality-book",
    title: "Conspirituality: How New Age Spirituality Became a Vector for QAnon and Political Extremism",
    author: "Charlotte Ward, Ollie Kendal, Matthew Remski",
    traditionSlug: "general",
    perspectiveType: "questioning",
    type: "book",
    summary: "Academic investigation into how New Age spirituality and wellness culture became recruitment vectors for conspiracy theories and QAnon, tracing the radicalization pathways through spiritual communities",
    sourceUrl: "https://www.simonandschuster.com/books/Conspirituality/Charlotte-Ward/9781492242529",
    license: "Copyright - Fair use permitted for educational review",
    priority: 4,
    difficulty: "intermediate",
    format: "book",
    affiliateEligible: true,
    datePublished: "2024-04-16",
    tags: [],
  },
  {
    slug: "conspirituality-podcast",
    title: "Conspirituality Podcast",
    author: "Cerie Bullivant & Julian Robles",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Podcast examining the intersection of conspiracy theories, wellness culture, and spirituality. Tracks how new-age and wellness communities became vectors for QAnon and other conspiracy movements.",
    sourceUrl: "conspirituality.net",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "podcast-app",
    datePublished: "2018-ongoing",
    tags: ["podcast","conspiracy","wellness","new-age","QAnon"],
  },
  {
    slug: "educated-westover",
    title: "Educated",
    author: "Tara Westover",
    traditionSlug: "christianity (fundamentalist/survivalist)",
    perspectiveType: "personal",
    type: "book",
    summary: "Tara Westover's memoir of growing up in a survivalist Mormon family in Idaho and eventually earning a PhD from Cambridge. Documents educational neglect and abuse in fundamentalist settings.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2018",
    tags: ["memoir","fundamentalism","education","survivalist"],
  },
  {
    slug: "gateway-podcast",
    title: "The Gateway: A Podcast About Conspiracy Theories",
    author: "Julian Feeld",
    traditionSlug: "general",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "In-depth podcast exploring how conspiracy theories operate as substitutes for spiritual and religious meaning-making, with interviews of former believers examining exit pathways",
    sourceUrl: "https://gateway.substack.com/",
    license: "Creative Commons",
    priority: 4,
    difficulty: "intermediate",
    format: "podcast",
    datePublished: "2021-01-01",
    tags: [],
  },
  {
    slug: "qanon-anonymous",
    title: "QAnon Anonymous Podcast",
    author: "Travis View, Cody Johnston, Marc-André Argentino",
    traditionSlug: "general",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Weekly deep-dive analysis of QAnon conspiracy theories and related online movements, featuring original reporting on radicalization pathways and strategies for exit and recovery",
    sourceUrl: "https://www.qanonautics.com/",
    license: "Creative Commons - CC BY-NC-SA 4.0",
    priority: 5,
    difficulty: "intermediate",
    format: "podcast",
    datePublished: "2018-06-01",
    tags: [],
  },
  {
    slug: "qanon-casualties",
    title: "QAnon Casualties: Families Affected by Conspiracy Theory Radicalization",
    author: "QAnon Casualties Community",
    traditionSlug: "general",
    perspectiveType: "questioning",
    type: "website",
    summary: "Community forum and resource center for families torn apart by QAnon conspiracy theory radicalization, featuring support networks, educational resources, and reunion stories",
    sourceUrl: "https://www.qanoncasualties.com/",
    license: "Community-maintained resource",
    priority: 5,
    difficulty: "beginner",
    format: "website",
    datePublished: "2020-01-01",
    tags: [],
  },
  {
    slug: "recovering-religion-hotline",
    title: "Recovering from Religion Hotline",
    author: "Recovering from Religion",
    traditionSlug: "cross-tradition",
    perspectiveType: "questioning",
    type: "organization",
    summary: "The 1-84-I-DOUBT-IT helpline for people in crisis during deconstruction. Staffed by trained volunteers. The most important crisis resource in the deconstruction space.",
    sourceUrl: "recoveringfromreligion.org/hotline-project",
    license: "standard-copyright",
    priority: 5,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2013-ongoing",
    tags: ["hotline","crisis","support","cross-religion"],
  },
  {
    slug: "religious-trauma-articles",
    title: "Religious Trauma Syndrome Articles",
    author: "Dr. Marlene Winell",
    traditionSlug: "cross-tradition",
    perspectiveType: "academic",
    type: "academic",
    summary: "Dr. Marlene Winell's foundational articles on Religious Trauma Syndrome published in the British Association for Behavioural and Cognitive Psychotherapies journal.",
    sourceUrl: "journeyfree.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "2011",
    tags: ["RTS","academic","psychology","research"],
  },
  {
    slug: "republic-of-lies",
    title: "Republic of Lies: American Politics and the Manipulation of Truth",
    author: "Anna Merlan",
    traditionSlug: "general",
    perspectiveType: "questioning",
    type: "book",
    summary: "Investigative examination of how conspiracy theories and belief manipulation function in American political culture, tracing pathways from fringe to mainstream",
    sourceUrl: "https://www.penguinrandomhouse.com/books/545009/republic-of-lies-by-anna-merlan/",
    license: "Copyright - Fair use permitted for educational review",
    priority: 3,
    difficulty: "intermediate",
    format: "book",
    affiliateEligible: true,
    datePublished: "2019-10-29",
    tags: [],
  },
  {
    slug: "exhindu-subreddit",
    title: "r/exhindu",
    author: "Reddit Community",
    traditionSlug: "hinduism",
    perspectiveType: "questioning",
    type: "subreddit",
    summary: "Online community for ex-Hindus and those questioning Hindu beliefs.",
    sourceUrl: "reddit.com/r/exhindu",
    license: "reddit-tos",
    priority: 3,
    difficulty: "beginner",
    format: "reddit",
    datePublished: "2010-ongoing",
    tags: ["community","discussion","support"],
  },
  {
    slug: "god-market",
    title: "The God Market",
    author: "Meera Nanda",
    traditionSlug: "hinduism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Analysis of the relationship between Hindu nationalism, globalization, and religious politics in India.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2009",
    tags: ["hindutva","nationalism","politics","globalization"],
  },
  {
    slug: "iskcon-abuse",
    title: "ISKCON/Hare Krishna Abuse Documentation",
    author: "Court Records",
    traditionSlug: "hinduism (iskcon)",
    perspectiveType: "questioning",
    type: "court-document/reports",
    summary: "Court documents and reports documenting child sexual abuse within the International Society for Krishna Consciousness (ISKCON/Hare Krishna). A $400M lawsuit in 2000 exposed systemic abuse in ISKCON boarding schools.",
    sourceUrl: "various",
    hostedLocally: true,
    license: "public-domain",
    priority: 4,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "1998-2005",
    tags: ["ISKCON","child-abuse","court-documents","institutional"],
  },
  {
    slug: "nirmukta",
    title: "Nirmukta",
    author: "Indian Freethought Network",
    traditionSlug: "hinduism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Indian freethought and rationalist website examining Hindu superstitions, caste discrimination, and promoting scientific thinking.",
    sourceUrl: "nirmukta.com",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "2006-ongoing",
    tags: ["freethought","India","rationalism","caste"],
  },
  {
    slug: "why-not-hindu",
    title: "Why I Am Not a Hindu",
    author: "Kancha Ilaiah",
    traditionSlug: "hinduism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Kancha Ilaiah's examination of Hinduism from a Dalit perspective, critiquing the caste system and Brahminical ideology.",
    sourceUrl: "amazon.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1996",
    tags: ["caste","dalit","criticism","social-justice"],
  },
  {
    slug: "aawa",
    title: "AAWA (Advocates for Awareness of Watchtower Abuses)",
    author: "AAWA",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "organization",
    summary: "Advocacy organization dedicated to raising awareness about Watchtower institutional abuse and supporting survivors",
    sourceUrl: "https://www.aawa.co",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["organization","advocacy","abuse-awareness"],
  },
  {
    slug: "australian-royal-commission",
    title: "Australian Royal Commission Case Study 29",
    author: "Royal Commission into Institutional Responses to Child Sexual Abuse",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "gov-document",
    summary: "Government investigation documenting 1,006 alleged perpetrators within JW organization, none reported to police by the Watchtower",
    sourceUrl: "https://www.childabuseroyalcommission.gov.au",
    hostedLocally: true,
    license: "public-domain",
    difficulty: "advanced",
    format: "free-online",
    tags: ["child-abuse","government","institutional-failure"],
  },
  {
    slug: "captives-of-a-concept",
    title: "Captives of a Concept",
    author: "Don Cameron",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "book",
    summary: "Critical examination of JW's foundational 1919 claim of divine appointment, the basis of organizational authority",
    sourceUrl: "https://www.amazon.com/Captives-Concept-Foundations-Jehovahs-Witnesses/dp/0967206634",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["doctrine","1919-claim","foundational-analysis"],
  },
  {
    slug: "crisis-of-conscience",
    title: "Crisis of Conscience",
    author: "Raymond Franz",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "personal",
    type: "book",
    summary: "Former Governing Body member's firsthand account of systemic doctrinal corruption and organizational dysfunction",
    sourceUrl: "https://www.amazon.com/Crisis-Conscience-Organized-Religion-Individual/dp/0914675311",
    license: "standard-copyright",
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["memoir","governing-body","insider-account"],
  },
  {
    slug: "dateline-2020-jw",
    title: "Dateline/20-20 JW Investigations",
    author: "NBC News / ABC News",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "tv-series",
    summary: "Investigative television reports by Dateline NBC and 20/20 on child sexual abuse cover-ups within Jehovah's Witnesses",
    sourceUrl: "https://www.nbc.com",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "streaming",
    tags: ["tv-news","child-abuse","mainstream-journalism"],
  },
  {
    slug: "exjw-critical-thinker",
    title: "Ex-JW Critical Thinker",
    author: "ExJW Critical Thinker",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "YouTube channel applying critical thinking and logical analysis to JW doctrine and institutional claims",
    sourceUrl: "https://www.youtube.com/@ExJWCriticalThinker",
    license: "youtube-standard",
    difficulty: "intermediate",
    format: "youtube",
    tags: ["youtube","analysis","critical-thinking"],
  },
  {
    slug: "exjw-subreddit",
    title: "r/exjw Community",
    author: "r/exjw Moderators",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "subreddit",
    summary: "Active community of 100,000+ former and questioning Jehovah's Witnesses sharing experiences and mutual support",
    sourceUrl: "https://www.reddit.com/r/exjw",
    license: "reddit-tos",
    difficulty: "beginner",
    format: "reddit",
    tags: ["community","support","peer-support"],
  },
  {
    slug: "in-search-christian-freedom",
    title: "In Search of Christian Freedom",
    author: "Raymond Franz",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "book",
    summary: "Raymond Franz's comprehensive analysis of JW doctrinal claims and their biblical foundations",
    sourceUrl: "https://www.amazon.com/Search-Christian-Freedom-Raymond-Franz/dp/0945756062",
    license: "standard-copyright",
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["doctrine","analysis","theological-critique"],
  },
  {
    slug: "jw-child-abuse-db",
    title: "JW Child Abuse Database",
    author: "JW Child Abuse Database Team",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "website",
    summary: "Searchable database documenting reported cases of child sexual abuse within Jehovah's Witnesses congregations",
    sourceUrl: "https://www.jwchildabuse.org",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["child-abuse","database","documentation"],
  },
  {
    slug: "jw-support",
    title: "JW.support",
    author: "JW Support Community",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "website",
    summary: "Practical support resources for those leaving Jehovah's Witnesses, including mental health guidance and reintegration help",
    sourceUrl: "https://www.jw.support",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "free-online",
    tags: ["support","transition","peer-support"],
  },
  {
    slug: "jwfacts",
    title: "JWFacts.com",
    author: "JWFacts Contributors",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "website",
    summary: "Comprehensive encyclopedia examining JW doctrine, history, and practices with extensive sourcing",
    sourceUrl: "https://www.jwfacts.com",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["encyclopedia","doctrine"],
  },
  {
    slug: "lloyd-evans",
    title: "Lloyd Evans / JW Watch",
    author: "Lloyd Evans",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "YouTube channel providing critical commentary on JW news, policy changes, and institutional issues",
    sourceUrl: "https://www.youtube.com/@LloydEvans",
    license: "youtube-standard",
    difficulty: "intermediate",
    format: "youtube",
    tags: ["youtube","news","activism","commentary"],
  },
  {
    slug: "reluctant-apostate",
    title: "The Reluctant Apostate",
    author: "Lloyd Evans",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "personal",
    type: "book",
    summary: "Lloyd Evans' memoir of leaving Jehovah's Witnesses and becoming a prominent activist and critic",
    sourceUrl: "https://www.amazon.com/Reluctant-Apostate-Leaving-Jehovahs-Witnesses/dp/0991637135",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["memoir","activism","personal-journey"],
  },
  {
    slug: "shunned-podcast",
    title: "Shunned Podcast",
    author: "Shunned Productions",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Podcast focused specifically on the practice and impact of disfellowshipping and shunning in Jehovah's Witnesses",
    sourceUrl: "https://www.shunnedpodcast.com",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "podcast-app",
    tags: ["podcast","shunning","family-impact"],
  },
  {
    slug: "the-witnesses-oxygen",
    title: "The Witnesses (Oxygen, 2021)",
    author: "Oxygen Network",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Four-part Oxygen documentary series examining JW institutional responses to child sexual abuse",
    sourceUrl: "https://www.oxygen.com",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "streaming",
    tags: ["documentary","child-abuse","mainstream-media"],
  },
  {
    slug: "this-jw-life",
    title: "This JW Life Podcast",
    author: "This JW Life Productions",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "personal",
    type: "podcast",
    summary: "Long-form podcast featuring in-depth interviews with current and former JW members sharing their experiences",
    sourceUrl: "https://www.thisjwlife.com",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "podcast-app",
    tags: ["podcast","memoir","oral-history"],
  },
  {
    slug: "watchtower-documents",
    title: "Watchtower Documents Archive",
    author: "Watchtower Documents Team",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "website",
    summary: "Archive of internal Watchtower organizational documents, correspondence, and unpublished materials",
    sourceUrl: "https://www.watchtowerdocuments.org",
    license: "standard-copyright",
    difficulty: "advanced",
    format: "free-online",
    tags: ["documents","archive","internal-communications"],
  },
  {
    slug: "witness-underground",
    title: "Witness Underground",
    author: "Witness Underground Productions",
    traditionSlug: "jehovahs-witnesses",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Documentary exploring Jehovah's Witnesses in the punk rock community and resistance to authoritarian control",
    sourceUrl: "https://www.witnessunderground.com",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "streaming",
    tags: ["documentary","punk-rock","cultural-resistance"],
  },
  {
    slug: "1832-first-vision",
    title: "1832 First Vision Account",
    author: "Joseph Smith",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "document",
    summary: "Joseph Smith's earliest known account of the First Vision, written in his own hand in 1832. Significantly differs from the official 1838 version—mentions only one divine personage rather than two.",
    sourceUrl: "https://josephsmithpapers.org",
    hostedLocally: true,
    license: "public-domain",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "1832",
    tags: ["first-vision","church-history","primary-source"],
  },
  {
    slug: "ces-letter",
    title: "CES Letter",
    author: "Jeremy Runnells",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "document",
    summary: "84-page comprehensive letter cataloging issues with LDS truth claims including Book of Mormon anachronisms, Book of Abraham problems, First Vision contradictions, and more.",
    sourceUrl: "https://cesletter.org",
    hostedLocally: true,
    license: "cc-by-nc-nd",
    priority: 5,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "2013",
    tags: ["apologetics","church-history","book-of-mormon","book-of-abraham"],
  },
  {
    slug: "exmormon-foundation",
    title: "ExMormon Foundation",
    author: "ExMormon Foundation",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "organization",
    summary: "Nonprofit organization hosting annual conferences bringing together ex-Mormon scholars, authors, and community members. Provides networking and educational resources.",
    sourceUrl: "https://exmormonfoundation.org",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2012",
    tags: ["organization","support","conferences","community"],
  },
  {
    slug: "exmormon-subreddit",
    title: "r/exmormon Subreddit",
    author: "Community moderated",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "subreddit",
    summary: "The largest online ex-Mormon community with 300,000+ members. Active daily discussions covering faith transitions, family relationships, temple experiences, and support.",
    sourceUrl: "https://reddit.com/r/exmormon",
    license: "reddit-tos",
    priority: 5,
    difficulty: "beginner",
    format: "reddit",
    datePublished: "2008",
    tags: ["community","support","stories"],
  },
  {
    slug: "fairmormon",
    title: "FairMormon / FAIR Latter-day Saints",
    author: "FAIR Latter-day Saints",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "website",
    summary: "The largest volunteer LDS apologetics organization. Their attempts to defend problematic issues often draw more attention to the problems. Many ex-Mormons report FAIR's responses accelerated their deconstruction.",
    sourceUrl: "https://fairlatterdaysaints.org",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "2001",
    tags: ["apologetics","counter-arguments","church-defense"],
  },
  {
    slug: "in-sacred-loneliness",
    title: "In Sacred Loneliness",
    author: "Todd Compton",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Biographical study of Joseph Smith's 33 plural wives. Documents the experiences of each wife. Essential reading for understanding the scope and impact of early Mormon polygamy.",
    sourceUrl: "https://www.amazon.com/Sacred-Loneliness-Wives-Joseph-Smith/dp/193326110X",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1997",
    tags: ["polygamy","joseph-smith","women","biography"],
  },
  {
    slug: "infants-on-thrones",
    title: "Infants on Thrones",
    author: "Panel of ex-Mormon friends",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Panel-style podcast by ex-Mormon friends using humor and intellectual discussion to examine LDS topics and broader philosophical questions about religion and meaning.",
    sourceUrl: "https://infantsonthrones.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "podcast-app",
    datePublished: "2012",
    tags: ["podcast","humor","philosophy","deconstruction"],
  },
  {
    slug: "insiders-view",
    title: "An Insider's View of Mormon Origins",
    author: "Grant Palmer",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Written by a 34-year CES employee and institute director, this book examines the origins of Mormonism using historical methodology. Palmer was disfellowshipped for publishing it.",
    sourceUrl: "https://www.amazon.com/Insiders-View-Mormon-Origins-Grant-Palmer/dp/1560851880",
    license: "standard-copyright",
    priority: 4,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2002",
    tags: ["church-history","origins","book-of-mormon","scholarship"],
  },
  {
    slug: "joseph-smith-papers",
    title: "Joseph Smith Papers Project",
    author: "The Church of Jesus Christ of Latter-day Saints",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Official LDS Church-sponsored project digitizing Joseph Smith's papers, journals, and documents. Makes previously restricted primary sources publicly available.",
    sourceUrl: "https://josephsmithpapers.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "2008",
    tags: ["primary-source","church-history","joseph-smith","scholarship"],
  },
  {
    slug: "lds-gospel-topics-essays",
    title: "LDS Gospel Topics Essays",
    author: "The Church of Jesus Christ of Latter-day Saints",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Official LDS Church essays acknowledging previously denied or minimized historical issues including Joseph Smith's polygamy, Book of Abraham translation problems, and priesthood ban on Black members.",
    sourceUrl: "https://churchofjesuschrist.org/study/manual/gospel-topics-essays",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "2013-2014",
    tags: ["church-history","polygamy","book-of-abraham","race","first-vision"],
  },
  {
    slug: "letter-for-my-wife",
    title: "Letter for My Wife",
    author: "Thomas Faulk",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "document",
    summary: "Comprehensive document addressing LDS truth claims written specifically for a believing spouse. More accessible and empathetic in tone than the CES Letter, with additional focus on emotional impact.",
    sourceUrl: "https://letterformywife.com",
    hostedLocally: true,
    license: "informal-free",
    priority: 5,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2016",
    tags: ["church-history","apologetics","relationships"],
  },
  {
    slug: "mormon-expression",
    title: "Mormon Expression (Archived)",
    author: "John Larsen",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Influential early ex-Mormon podcast (2009-2015) hosted by John Larsen. Now archived but episodes remain valuable for in-depth historical analysis.",
    sourceUrl: "https://mormonexpression.org",
    license: "standard-copyright",
    priority: 2,
    difficulty: "intermediate",
    format: "podcast-app",
    datePublished: "2009",
    tags: ["podcast","church-history","analysis","archived"],
  },
  {
    slug: "mormon-hierarchy-quinn",
    title: "The Mormon Hierarchy Series",
    author: "D. Michael Quinn",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Multi-volume academic series examining the origins of power, extensions of power, and wealth/corporate structure of the LDS Church hierarchy. Excommunicated historian Quinn's deeply researched work.",
    sourceUrl: "https://www.amazon.com/Mormon-Hierarchy-Origins-Michael-Quinn/dp/1560850329",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1994-2012",
    tags: ["church-history","leadership","power","scholarship"],
  },
  {
    slug: "mormon-stories",
    title: "Mormon Stories Podcast",
    author: "John Dehlin",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Long-running podcast (1,700+ episodes) featuring in-depth interviews with ex-Mormons, scholars, and Church critics hosted by John Dehlin, excommunicated in 2015.",
    sourceUrl: "https://mormonstories.org",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "podcast-app",
    datePublished: "2005",
    tags: ["podcast","interviews","church-history","personal-stories"],
  },
  {
    slug: "mormonessays",
    title: "MormonEssays.com",
    author: "Third-party indexer",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Third-party index making the LDS Church's Gospel Topics Essays easier to find and navigate. The Church buried these essays deep in its website—this site brings them to the surface.",
    sourceUrl: "https://mormonessays.com",
    license: "standard-copyright",
    priority: 2,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2015",
    tags: ["church-history","index","gospel-topics-essays"],
  },
  {
    slug: "mormonthink",
    title: "MormonThink.com",
    author: "Multiple contributors",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "website",
    summary: "Comprehensive encyclopedia-style website examining LDS truth claims from multiple perspectives. Presents both faithful and critical viewpoints on each topic.",
    sourceUrl: "https://mormonthink.com",
    license: "standard-copyright",
    priority: 5,
    difficulty: "intermediate",
    format: "free-online",
    datePublished: "2005",
    tags: ["apologetics","church-history","encyclopedia"],
  },
  {
    slug: "murder-among-mormons",
    title: "Murder Among the Mormons (Netflix)",
    author: "Netflix",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Netflix documentary about Mark Hofmann, who forged early Mormon documents and committed murder to cover it up. Reveals Church leadership's willingness to suppress documents that contradicted official history.",
    sourceUrl: "https://netflix.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "streaming",
    datePublished: "2021",
    tags: ["documentary","forgery","mark-hofmann","church-history"],
  },
  {
    slug: "nemo-the-mormon",
    title: "Nemo the Mormon",
    author: "Nemo the Mormon",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "YouTube channel analyzing LDS Church history, truth claims, and current events. Known for well-produced videos with clear explanations of complex historical issues.",
    sourceUrl: "https://youtube.com/@nemothemcmormon",
    license: "youtube-standard",
    priority: 3,
    difficulty: "intermediate",
    format: "youtube",
    datePublished: "2016",
    tags: ["youtube","church-history","analysis"],
  },
  {
    slug: "no-man-knows-my-history",
    title: "No Man Knows My History",
    author: "Fawn Brodie",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "book",
    summary: "Groundbreaking 1945 biography of Joseph Smith by historian Fawn Brodie, a former member. The first serious scholarly examination of Smith's life that challenged the official Church narrative.",
    sourceUrl: "https://www.amazon.com/No-Man-Knows-History-Joseph/dp/0679734155",
    license: "standard-copyright",
    priority: 5,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "1945",
    tags: ["biography","church-history","joseph-smith"],
  },
  {
    slug: "postmormonlife",
    title: "PostMormonLife.com",
    author: "PostMormonLife",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Website providing practical resources for life after Mormonism—from social adjustment to family relationships to finding community outside the Church.",
    sourceUrl: "https://postmormonlife.com",
    license: "standard-copyright",
    priority: 2,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2013",
    tags: ["support","practical","transition","community"],
  },
  {
    slug: "quitmormon",
    title: "QuitMormon.com",
    author: "Mark Naugle",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Free legal service processing official LDS Church membership resignations. Founded by attorney Mark Naugle, has processed tens of thousands of resignations.",
    sourceUrl: "https://quitmormon.com",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2012",
    tags: ["resignation","legal","practical"],
  },
  {
    slug: "radio-free-mormon",
    title: "Radio Free Mormon Podcast",
    author: "Dan Wees",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "podcast",
    summary: "Podcast by a former active Mormon analyzing LDS Church history, apologetics, and current events with legal precision. Known for detailed, well-researched episodes examining Church truth claims.",
    sourceUrl: "https://radiofreemormon.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "advanced",
    format: "podcast-app",
    datePublished: "2015",
    tags: ["podcast","apologetics","church-history","legal"],
  },
  {
    slug: "rough-stone-rolling",
    title: "Rough Stone Rolling",
    author: "Richard Bushman",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "book",
    summary: "2005 biography of Joseph Smith by believing LDS historian Richard Bushman. Acknowledges many historical problems while attempting faithful interpretations.",
    sourceUrl: "https://www.amazon.com/Rough-Stone-Rolling-Joseph-Smith/dp/0375254765",
    license: "standard-copyright",
    priority: 3,
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2005",
    tags: ["biography","joseph-smith","church-history","scholarship"],
  },
  {
    slug: "sandra-tanner-utlm",
    title: "Sandra Tanner & Utah Lighthouse Ministry",
    author: "Sandra and Jerald Tanner",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "website",
    summary: "Founded by Sandra and Jerald Tanner, the longest-running Mormon criticism ministry since the 1960s. Sandra Tanner is a great-great-granddaughter of Brigham Young.",
    sourceUrl: "https://utlm.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "advanced",
    format: "free-online",
    datePublished: "1964",
    tags: ["church-history","apologetics","pioneer"],
  },
  {
    slug: "the-mormons-pbs",
    title: "The Mormons (PBS Documentary)",
    author: "PBS Frontline / American Experience",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "documentary",
    summary: "Four-hour PBS Frontline/American Experience documentary examining the history and culture of the LDS Church. Balanced but thorough exploration of major issues.",
    sourceUrl: "https://pbs.org",
    license: "standard-copyright",
    priority: 4,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2007",
    tags: ["documentary","church-history","culture","overview"],
  },
  {
    slug: "under-the-banner-book",
    title: "Under the Banner of Heaven",
    author: "Jon Krakauer",
    traditionSlug: "mormonism",
    perspectiveType: "academic",
    type: "book",
    summary: "2003 investigative book examining the violent fundamentalist fringes of Mormonism through the lens of the 1984 Lafferty murders. Connects modern fundamentalist violence to foundational Mormon history.",
    sourceUrl: "https://www.amazon.com/Under-Banner-Heaven-Story-Violent-Extremists/dp/0385509537",
    license: "standard-copyright",
    priority: 4,
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    datePublished: "2003",
    tags: ["fundamentalism","violence","polygamy","history"],
  },
  {
    slug: "under-the-banner-hulu",
    title: "Under the Banner of Heaven (Hulu Series)",
    author: "Hulu",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "tv-series",
    summary: "2022 Hulu adaptation of Krakauer's book, starring Andrew Garfield as a detective investigating the Lafferty murders. Dramatizes the intersection of fundamentalist Mormon beliefs and violence.",
    sourceUrl: "https://hulu.com",
    license: "standard-copyright",
    priority: 2,
    difficulty: "beginner",
    format: "streaming",
    datePublished: "2022",
    tags: ["tv-series","drama","fundamentalism","true-crime"],
  },
  {
    slug: "wasmormon",
    title: "WasMormon.org",
    author: "Community moderated",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "website",
    summary: "Website collecting profiles and stories of people who have left the LDS Church. Users share their journey from belief to deconstruction.",
    sourceUrl: "https://wasmormon.org",
    license: "standard-copyright",
    priority: 3,
    difficulty: "beginner",
    format: "free-online",
    datePublished: "2014",
    tags: ["stories","profiles","community"],
  },
  {
    slug: "year-of-polygamy",
    title: "Year of Polygamy",
    author: "Lindsay Hansen Park",
    traditionSlug: "mormonism",
    perspectiveType: "questioning",
    type: "podcast",
    summary: "Podcast dedicated to examining the history of polygamy in Mormonism. Lindsay Hansen Park interviews historians, descendants, and current polygamous community members.",
    sourceUrl: "https://yearofpolygamy.com",
    license: "standard-copyright",
    priority: 3,
    difficulty: "intermediate",
    format: "podcast-app",
    datePublished: "2013",
    tags: ["podcast","polygamy","women","church-history"],
  },
  {
    slug: "zelph-on-the-shelf",
    title: "Zelph on the Shelf",
    author: "Zelph on the Shelf",
    traditionSlug: "mormonism",
    perspectiveType: "devotional",
    type: "youtube",
    summary: "YouTube channel using humor and accessibility to examine LDS truth claims. Named after a Book of Mormon figure Joseph Smith claimed to have found.",
    sourceUrl: "https://youtube.com/c/ZelphOnTheShelf",
    license: "youtube-standard",
    priority: 3,
    difficulty: "beginner",
    format: "youtube",
    datePublished: "2016",
    tags: ["youtube","humor","church-history","apologetics"],
  },
  {
    slug: "aftermath-foundation",
    title: "The Aftermath Foundation",
    author: "Leah Remini",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "organization",
    summary: "Non-profit organization founded by Leah Remini providing financial and emotional support to people leaving Scientology. Offers exit counseling, housing assistance, legal support, and community resources.",
    sourceUrl: "https://www.theaftermathfoundation.org/",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "free-online",
    tags: ["nonprofit","support","escape"],
  },
  {
    slug: "bite-model-hassan",
    title: "BITE Model / Freedom of Mind",
    author: "Steve Hassan",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "website",
    summary: "Steve Hassan's BITE Model (Behavior, Information, Thought, Emotion) is the most influential framework for analyzing undue influence and coercive control. Essential theoretical lens for deconstructing Scientology's mechanisms. PDF resources freely available with attribution required.",
    sourceUrl: "https://freedomofmind.com/",
    hostedLocally: true,
    license: "TM-copyright-hassan",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["cult-analysis","psychology","framework"],
  },
  {
    slug: "blown-for-good",
    title: "Blown for Good: Behind the Iron Curtain of Scientology",
    author: "Marc Headley",
    traditionSlug: "scientology",
    perspectiveType: "personal",
    type: "book",
    summary: "Marc Headley's memoir detailing his 27 years in Scientology's Sea Org at the International Base. Documents daily conditions, forced labor, abuse, and his eventual escape. Essential firsthand account of the upper echelons of the organization.",
    sourceUrl: "https://www.amazon.com/Blown-Good-Behind-Curtain-Scientology/dp/1597990418",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["memoir","sea-org","escape"],
  },
  {
    slug: "chris-shelton",
    title: "Chris Shelton - Sensibly Speaking",
    author: "Chris Shelton",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "youtube",
    summary: "Former Sea Org member Chris Shelton provides detailed analysis and criticism of Scientology on YouTube. In-depth breakdowns of Scientology's teachings, organizational structure, and practices from an insider perspective.",
    sourceUrl: "https://www.youtube.com/c/ChrisShelton",
    license: "youtube-standard",
    difficulty: "intermediate",
    format: "youtube",
    tags: ["youtube","analysis","insider"],
  },
  {
    slug: "combating-cult-mind-control",
    title: "Combating Cult Mind Control",
    author: "Steve Hassan",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "book",
    summary: "Foundational book on mind control and coercive persuasion. While not Scientology-specific, Hassan's framework and case studies illuminate how high-control groups operate, including detailed Scientology analysis.",
    sourceUrl: "https://www.amazon.com/Combating-Cult-Mind-Control-Updated/dp/0996246703",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["psychology","cult-tactics","recovery"],
  },
  {
    slug: "fair-game-podcast",
    title: "Fair Game Podcast",
    author: "Leah Remini, Mike Rinder",
    traditionSlug: "scientology",
    perspectiveType: "academic",
    type: "podcast",
    summary: "Continuation of the Scientology and the Aftermath investigation in podcast format. Leah Remini and Mike Rinder conduct deep-dive interviews exploring specific cases, organizational practices, and escape stories.",
    sourceUrl: "https://fairgamepodcast.com/",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "podcast-app",
    tags: ["podcast","investigation"],
  },
  {
    slug: "fishman-affidavit",
    title: "Fishman Affidavit / OT Materials",
    author: "Steven Fishman",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "court-document",
    summary: "Court filing containing Scientology's secret OT (Operating Thetan) materials. Originally sealed but entered into public record. Essential source on Scientology's esoteric teachings. Link to court archives only; do not host directly due to ongoing IP disputes.",
    sourceUrl: "https://cs.cmu.edu/~dst/Library/",
    hostedLocally: true,
    license: "public-domain",
    difficulty: "advanced",
    format: "free-online",
    tags: ["court-document","OT-materials","legal"],
  },
  {
    slug: "going-clear-book",
    title: "Going Clear: Scientology and the Prison of Belief",
    author: "Lawrence Wright",
    traditionSlug: "scientology",
    perspectiveType: "academic",
    type: "book",
    summary: "Pulitzer Prize-winning journalist Lawrence Wright's definitive investigation into Scientology. Combines historical research, interviews with former members, and court documents to expose the organization's practices and inner workings.",
    sourceUrl: "https://www.amazon.com/Going-Clear-Scientology-Prison-Belief/dp/0307700666",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["investigation","history","hubbard"],
  },
  {
    slug: "going-clear-hbo",
    title: "Going Clear: Scientology and the Prison of Belief (HBO Documentary)",
    author: "Alex Gibney",
    traditionSlug: "scientology",
    perspectiveType: "academic",
    type: "documentary",
    summary: "Emmy-winning HBO documentary directed by Alex Gibney. Visual investigation of Scientology featuring interviews with former Sea Org members, featuring dramatic firsthand accounts of disconnection, Fair Game, and escape.",
    sourceUrl: "https://www.hbo.com/documentaries/going-clear-scientology-and-the-prison-of-belief",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "streaming",
    tags: ["documentary","investigation"],
  },
  {
    slug: "headley-v-scientology",
    title: "Headley v. Church of Scientology",
    author: "Federal Court System",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "court-document",
    summary: "Federal lawsuit filed by Marc Headley alleging forced labor, human trafficking, and wage theft while he worked in Scientology's International Base in California. Landmark case for labor rights in high-control organizations.",
    sourceUrl: "https://www.justia.com/",
    hostedLocally: true,
    license: "public-domain",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["court-document","labor","trafficking"],
  },
  {
    slug: "lisa-mcpherson",
    title: "Lisa McPherson Case Filings",
    author: "Florida Court System",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "court-document",
    summary: "Wrongful death lawsuit filings documenting the case of Lisa McPherson, who died in 1995 while under Scientology's control during a forced 'Introspection Rundown.' Critical documentation of organizational negligence and the Introspection Rundown practice.",
    sourceUrl: "https://www.flcourts.org/",
    hostedLocally: true,
    license: "public-domain",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["court-document","death","negligence"],
  },
  {
    slug: "mike-rinder-blog",
    title: "Mike Rinder's Blog (Archive)",
    author: "Mike Rinder",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "website",
    summary: "Former Scientology executive Mike Rinder's detailed blog documenting organizational practices and abuses. Blog archived after Rinder's death in January 2025. As former head of the OSA (Office of Special Affairs), Rinder provided insider perspective on Fair Game tactics and organizational control.",
    sourceUrl: "https://mikerindersblog.org/",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["blog","insider"],
  },
  {
    slug: "operation-clambake",
    title: "Operation Clambake (xenu.net)",
    author: "Arnie Lerma",
    traditionSlug: "scientology",
    perspectiveType: "academic",
    type: "website",
    summary: "The oldest continuously-running anti-Scientology website, active since 1996. Comprehensive encyclopedia of Scientology information, internal documents, court filings, and historical research. Essential historical archive.",
    sourceUrl: "https://xenu.net/",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["encyclopedia","history"],
  },
  {
    slug: "piece-of-blue-sky",
    title: "A Piece of Blue Sky: Scientology, Dianetics and L. Ron Hubbard Exposed",
    author: "Jon Atack",
    traditionSlug: "scientology",
    perspectiveType: "academic",
    type: "book",
    summary: "Comprehensive historical investigation of Scientology and L. Ron Hubbard's background. Documents Hubbard's fabricated autobiography, early organizational practices, and the development of Scientology's belief system.",
    sourceUrl: "https://www.amazon.com/Piece-Blue-Sky-Scientology-Dianetics/dp/0312042671",
    license: "standard-copyright",
    difficulty: "advanced",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["history","hubbard","comprehensive"],
  },
  {
    slug: "scientology-aftermath",
    title: "Scientology and the Aftermath",
    author: "Leah Remini, Mike Rinder",
    traditionSlug: "scientology",
    perspectiveType: "academic",
    type: "tv-series",
    summary: "Emmy-winning A&E series featuring actress Leah Remini and former Scientology executive Mike Rinder investigating documented abuses, disconnection cases, and organizational practices.",
    sourceUrl: "https://www.netflix.com/",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "streaming",
    tags: ["tv-series","investigation","abuse"],
  },
  {
    slug: "scientology-money-project",
    title: "Scientology Money Project",
    author: "Jefferson Hawkins",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "website",
    summary: "Deep investigation of Scientology's financial practices, fundraising methods, and economic impact on members. Documents the financial exploitation through mandatory donations and the Bridge to Total Freedom.",
    sourceUrl: "https://scientologymoneyproject.com/",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["finances","exploitation"],
  },
  {
    slug: "scientology-subreddit",
    title: "r/Scientology",
    author: "Reddit Community",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "subreddit",
    summary: "Active subreddit for discussing Scientology. Moderated community featuring ex-members, current researchers, and family members of Scientology members sharing experiences and information.",
    sourceUrl: "https://www.reddit.com/r/Scientology/",
    license: "reddit-tos",
    difficulty: "beginner",
    format: "reddit",
    tags: ["community","discussion"],
  },
  {
    slug: "troublemaker-remini",
    title: "Troublemaker: Surviving Hollywood and Scientology",
    author: "Leah Remini",
    traditionSlug: "scientology",
    perspectiveType: "personal",
    type: "book",
    summary: "Actress Leah Remini's candid memoir detailing her 34-year involvement with Scientology, her exit, and her journey to becoming one of the organization's most public critics.",
    sourceUrl: "https://www.amazon.com/Troublemaker-Surviving-Hollywood-Scientology-Remini/dp/0345802969",
    license: "standard-copyright",
    difficulty: "beginner",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["memoir","celebrity"],
  },
  {
    slug: "unbreakable-miss-lovely",
    title: "The Unbreakable Miss Lovely: How the Church of Scientology Tried to Destroy a Woman and Failed",
    author: "Tony Ortega",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "book",
    summary: "Tony Ortega's account of Paulette Cooper, journalist targeted by Scientology's Operation Freakout—the organization's documented campaign to destroy her through harassment, fraud, and psychological warfare.",
    sourceUrl: "https://www.amazon.com/Unbreakable-Miss-Lovely-Scientology-Destroyed/dp/1492214531",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "paid-book",
    affiliateEligible: true,
    tags: ["fair-game","harassment"],
  },
  {
    slug: "underground-bunker",
    title: "The Underground Bunker",
    author: "Tony Ortega",
    traditionSlug: "scientology",
    perspectiveType: "questioning",
    type: "website",
    summary: "Tony Ortega's daily blog providing the most consistent, current Scientology coverage including breaking news on litigation, organizational changes, and former member reports. Essential daily monitoring resource.",
    sourceUrl: "https://tonyortega.org/",
    license: "standard-copyright",
    difficulty: "intermediate",
    format: "free-online",
    tags: ["blog","news","daily"],
  },
];

export function getAllResources(): Resource[] {
  return resources;
}

export function getResourceBySlug(slug: string): Resource | undefined {
  return resources.find((r) => r.slug === slug);
}

export function getResourcesByTradition(traditionSlug: string): Resource[] {
  return resources.filter((r) => r.traditionSlug === traditionSlug);
}

export function getResourcesByPerspective(
  type: Resource["perspectiveType"]
): Resource[] {
  return resources.filter((r) => r.perspectiveType === type);
}

export function getPairedResource(slug: string): Resource | undefined {
  const resource = getResourceBySlug(slug);
  if (!resource?.pairedWith) return undefined;
  return getResourceBySlug(resource.pairedWith);
}

export function getResourcesByType(type: string): Resource[] {
  return resources.filter((r) => r.type === type);
}

export function getResourcesByTag(tag: string): Resource[] {
  return resources.filter((r) => r.tags.includes(tag));
}

export function getAllResourceTypes(): string[] {
  return [...new Set(resources.map((r) => r.type))].sort();
}

export function getAllTags(): string[] {
  return [...new Set(resources.flatMap((r) => r.tags))].sort();
}
