import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, Linking } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { useRouter } from 'expo-router';
import { colors, gradientProps, screenGradient } from '../lib/theme';

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using RoutineX ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.',
  },
  {
    title: '2. Description of Service',
    body: 'RoutineX provides AI-powered video analysis for competitive dance routines. The Service generates scores, feedback, and improvement suggestions based on uploaded video content. All analyses are generated by artificial intelligence and are intended for educational and practice purposes only.',
  },
  {
    title: '3. Accounts & Eligibility',
    body: 'You must be at least 13 years old to create an account. If you are under 18, a parent or guardian must agree to these terms on your behalf. You are responsible for maintaining the security of your account credentials.',
  },
  {
    title: '4. Payments & Refunds',
    body: 'Single analyses are $8.99 USD each, or you can purchase a Competition Pack of 5 analyses for $29.99 USD. All payments are processed through Stripe. Refunds are handled on a case-by-case basis — contact us at the email below.',
  },
  {
    title: '5. User Content',
    body: 'You retain ownership of all videos and content you submit. Your video is processed entirely on your device — it is never uploaded to our servers. Only small still-frame thumbnails are sent to our AI provider for analysis. Frames are automatically deleted within 24 hours of analysis completion, and you can request immediate deletion at any time from your analysis results page. We do not share your video or frames with third parties.',
  },
  {
    title: '6. AI Disclaimer',
    body: 'RoutineX analyses are generated by AI and should not be treated as official competition scores or professional coaching advice. Scores and feedback are approximations intended to help dancers and parents identify areas for improvement. RoutineX is not affiliated with any competition organization.',
  },
  {
    title: '7. Prohibited Use',
    body: 'You may not use the Service to upload content you do not own or have permission to use, upload inappropriate or illegal content, attempt to reverse-engineer the Service, or use the Service in any way that violates applicable law.',
  },
  {
    title: '8. Limitation of Liability',
    body: 'RoutineX is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to inaccurate analysis results or service interruptions.',
  },
  {
    title: '9. Changes to Terms',
    body: 'We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the revised terms.',
  },
  {
    title: '10. Contact',
    body: 'Questions about these terms? Email us at danceroutinex@gmail.com.',
  },
];

export default function TermsScreen() {
  const router = useRouter();

  return (
    <LinearGradient colors={screenGradient as unknown as string[]} {...gradientProps.topToBottom} style={{ flex: 1 }}>
      <ScrollView contentContainerStyle={{ padding: 24, paddingTop: 56, paddingBottom: 48 }}>
        <TouchableOpacity onPress={() => router.back()} style={{ marginBottom: 20 }}>
          <Text style={{ color: colors.textSecondary, fontSize: 14 }}>← Back</Text>
        </TouchableOpacity>

        <Text style={{ color: '#fff', fontSize: 30, fontWeight: '800', letterSpacing: -0.5, marginBottom: 6 }}>
          Terms of Service
        </Text>
        <Text style={{ color: colors.textSecondary, fontSize: 13, marginBottom: 24 }}>
          Effective Date: March 17, 2026
        </Text>

        {sections.map((section) => (
          <View key={section.title} style={{ marginBottom: 24 }}>
            <Text style={{ color: '#fff', fontSize: 16, fontWeight: '700', marginBottom: 8 }}>
              {section.title}
            </Text>
            <Text style={{ color: colors.textSecondary, fontSize: 14, lineHeight: 22 }}>
              {section.body}
            </Text>
          </View>
        ))}

        <TouchableOpacity onPress={() => Linking.openURL('mailto:danceroutinex@gmail.com')} style={{ marginTop: 8 }}>
          <Text style={{ color: colors.primary[400], fontSize: 14, textDecorationLine: 'underline' }}>
            danceroutinex@gmail.com
          </Text>
        </TouchableOpacity>
      </ScrollView>
    </LinearGradient>
  );
}
