import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ReportView from "@/components/spotlight/ReportView";
import { SAMPLE } from "@/lib/spotlight/sample";

export const metadata: Metadata = {
  title: "Sample Spotlight report — what a $14.99 RoutineX breakdown looks like",
  description:
    "Read a full RoutineX Spotlight report: key moments with coaching lines drawn on the dancer's frames, measured angles, seven category scores, priorities, drills and a four-week plan.",
  alternates: { canonical: "/spotlight/sample" },
};

export default function SpotlightSamplePage() {
  if (!SAMPLE.report) notFound();
  return (
    <main data-stage-page className="min-h-screen pt-16">
      <div className="st-wrap pt-8">
        <p className="text-sm text-zinc-500">This is a complete sample report, generated by the Spotlight engine from AI-generated footage so no real dancer appears on the public site. Your report looks exactly like this — with your dancer in it.</p>
      </div>
      <ReportView
        report={SAMPLE.report}
        frames={SAMPLE.frames}
        urls={SAMPLE.urls}
        meta={SAMPLE.meta}
        sample
        actions={
          <>
            <Link href="/spotlight/new" className="st-btn st-btn-sunset !min-h-[2.5rem] !px-5 !py-2.5 !text-sm">Get this for your dancer — $14.99</Link>
            <a href="/spotlight-sample/RoutineX-Spotlight-Sample.pdf" className="st-btn st-btn-ghost !px-5 !py-2.5 !text-sm">Download the sample PDF</a>
          </>
        }
      />
    </main>
  );
}
