import { Sparkles } from "lucide-react";

export const metadata = {
  title: "Terms of Service",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen py-20 px-4">
      <div className="mx-auto max-w-3xl">
        <a href="/" className="inline-flex items-center gap-2 mb-10">
          <Sparkles className="h-6 w-6 text-primary-400" />
          <span className="text-lg font-bold">
            Routine<span className="gradient-text">X</span>
          </span>
        </a>

        <h1 className="text-3xl sm:text-4xl font-bold font-[family-name:var(--font-display)] mb-8">
          Terms of Service
        </h1>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-surface-200">
          <p><strong>Effective Date:</strong> March 17, 2026</p>

          <h2 className="text-lg font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using RoutineX (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
          </p>

          <h2 className="text-lg font-semibold text-white">2. Description of Service</h2>
          <p>
            RoutineX provides AI-powered video analysis for competitive dance routines. The Service generates scores, feedback, and improvement suggestions based on uploaded video content. All analyses are generated by artificial intelligence and are intended for educational and practice purposes only.
          </p>

          <h2 className="text-lg font-semibold text-white">3. Accounts & Eligibility</h2>
          <p>
            You must be at least 13 years old to create an account. If you are under 18, a parent or guardian must agree to these terms on your behalf. You are responsible for maintaining the security of your account credentials.
          </p>

          <h2 className="text-lg font-semibold text-white">4. Payments & Refunds</h2>
          <p>
            Membership requires a one-time fee of $4.99 USD, which includes 1 video analysis. Additional analyses: get 5 for $24.99. All payments are processed through Stripe. Refunds are handled on a case-by-case basis — contact us at the email below.
          </p>

          <h2 className="text-lg font-semibold text-white">5. User Content</h2>
          <p>
            You retain ownership of all videos and content you submit. Your video is processed entirely on your device — it is never uploaded to our servers. Only small still-frame thumbnails are sent to our AI provider for analysis. Frames are automatically deleted within 24 hours of analysis completion, and you can request immediate deletion at any time from your analysis results page. We do not share your video or frames with third parties.
          </p>

          <h2 className="text-lg font-semibold text-white">6. AI Disclaimer</h2>
          <p>
            RoutineX analyses are generated by AI and should not be treated as official competition scores or professional coaching advice. Scores and feedback are approximations intended to help dancers and parents identify areas for improvement. RoutineX is not affiliated with any competition organization.
          </p>

          <h2 className="text-lg font-semibold text-white">7. Prohibited Use</h2>
          <p>
            You may not use the Service to upload content you do not own or have permission to use, upload inappropriate or illegal content, attempt to reverse-engineer the Service, or use the Service in any way that violates applicable law.
          </p>

          <h2 className="text-lg font-semibold text-white">8. Limitation of Liability</h2>
          <p>
            RoutineX is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to inaccurate analysis results or service interruptions.
          </p>

          <h2 className="text-lg font-semibold text-white">9. Changes to Terms</h2>
          <p>
            We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the revised terms.
          </p>

          <h2 className="text-lg font-semibold text-white">10. Contact</h2>
          <p>
            Questions about these terms? Email us at{" "}
            <a href="mailto:danceroutinex@gmail.com" className="text-primary-400 hover:text-primary-300">
              danceroutinex@gmail.com
            </a>.
          </p>
        </div>
      </div>
    </div>
  );
}
